"use client";

import dynamic from "next/dynamic";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { useDropzone } from "react-dropzone";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { ArrowDown, Camera, Check, ChevronRight, Clipboard, Download, ImagePlus, Layers3, RefreshCw, Share2, Sparkles, Upload, X } from "lucide-react";
import { Toaster, toast } from "sonner";
import { themes } from "@/data/themes";
import { builderNumber, generateTitle } from "@/lib/builder-title/generate-title";
import { prepareImage, loadImage } from "@/lib/image/process";
import { builderDetailsSchema } from "@/lib/validation/builder-details";
import { SHARE_CAPTION, xIntent } from "@/lib/share/x";
import type { BuilderDetails, CropConfig, ExportPayload, PreviewMode, ThemeId } from "@/types/builder";
import { BuilderPreview } from "@/components/preview/builder-preview";

const CropEditor=dynamic(()=>import("./crop-editor"),{ssr:false,loading:()=> <div className="crop-loading">Preparing crop controls…</div>});
const roleSuggestions=["Developer","Designer","Founder","Builder","Researcher","Engineer","Student","Product Engineer","Smart Contract Developer","Protocol Engineer","Community Builder","Open-Source Contributor"];
const stackSuggestions=["Soroban","Stellar","Rust","React","Next.js","TypeScript","Solidity","Move","AI","Backend","Full Stack","Mobile","Design","DevRel","Open Source","Infrastructure"];
const emptyDetails: BuilderDetails={name:"",role:"",stack:[],github:"",x:"",statement:""};
const defaultCrop:CropConfig={crop:{x:0,y:0},zoom:1,pixels:null};

export function BuilderGenerator(){
  const reduce=useReducedMotion();
  const [photo,setPhoto]=useState<string|null>(null); const photoRef=useRef<string|null>(null);
  const [processing,setProcessing]=useState(false); const [step,setStep]=useState(1); const [mode,setMode]=useState<PreviewMode>("card");
  const [details,setDetails]=useState<BuilderDetails>(emptyDetails); const [theme,setTheme]=useState<ThemeId>("genesis"); const [reroll,setReroll]=useState(0);
  const [cardCrop,setCardCrop]=useState<CropConfig>(defaultCrop); const [profileCrop,setProfileCrop]=useState<CropConfig>(defaultCrop); const [exporting,setExporting]=useState<string|null>(null);
  const [sessionSeed,setSessionSeed]=useState("hhgoa-session");
  const title=useMemo(()=>generateTitle(details,reroll),[details,reroll]); const number=useMemo(()=>builderNumber(details.name,sessionSeed),[details.name,sessionSeed]);
  const currentCrop=mode==="card"?cardCrop:profileCrop; const setCurrentCrop=mode==="card"?setCardCrop:setProfileCrop;
  const cropPosition=`${50-currentCrop.crop.x/3}% ${50-currentCrop.crop.y/3}%`;

  useEffect(()=>{try{const raw=sessionStorage.getItem("hhgoa-details");if(raw)setDetails({...emptyDetails,...JSON.parse(raw)});const t=sessionStorage.getItem("hhgoa-theme") as ThemeId;if(t&&themes[t])setTheme(t);let storedSeed=sessionStorage.getItem("hhgoa-seed");if(!storedSeed){storedSeed=crypto.randomUUID();sessionStorage.setItem("hhgoa-seed",storedSeed)}setSessionSeed(storedSeed);}catch{}},[]);
  useEffect(()=>{try{sessionStorage.setItem("hhgoa-details",JSON.stringify(details));sessionStorage.setItem("hhgoa-theme",theme)}catch{}},[details,theme]);
  useEffect(()=>{const paste=(event:ClipboardEvent)=>{const f=[...(event.clipboardData?.files??[])].find(x=>x.type.startsWith("image/"));if(f)void acceptFile(f)};window.addEventListener("paste",paste);return()=>window.removeEventListener("paste",paste)},[]);
  useEffect(()=>()=>{if(photoRef.current)URL.revokeObjectURL(photoRef.current)},[]);

  const acceptFile=useCallback(async(file:File)=>{setProcessing(true);try{const blob=await prepareImage(file);const url=URL.createObjectURL(blob);if(photoRef.current)URL.revokeObjectURL(photoRef.current);photoRef.current=url;setPhoto(url);setCardCrop(defaultCrop);setProfileCrop(defaultCrop);setStep(2);toast.success("Photo ready. Adjust the crop if needed.")}catch(error){toast.error(error instanceof Error?error.message:"Could not process that photo.")}finally{setProcessing(false)}},[]);
  const onDrop=useCallback((files:File[])=>{if(files[0])void acceptFile(files[0])},[acceptFile]);
  const {getRootProps,getInputProps,isDragActive,open}=useDropzone({onDrop,noClick:true,noKeyboard:true,multiple:false,accept:{"image/jpeg":[".jpg",".jpeg"],"image/png":[".png"],"image/webp":[".webp"],"image/heic":[".heic"],"image/heif":[".heif"]}});
  const valid=builderDetailsSchema.safeParse(details); const canExport=Boolean(photo&&valid.success&&!processing);
  const slug=(details.name||"builder").toLowerCase().normalize("NFKD").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,42)||"builder";

  async function createAssets(){if(!photo||!valid.success)throw new Error(valid.success?"Add a photo first":valid.error.issues[0]?.message);const image=await loadImage(photo);const mod=await import("@/lib/export/render");const payload:ExportPayload={details,title,number,theme,photo:image,cardCrop:cardCrop.pixels,profileCrop:profileCrop.pixels};const [card,profile,frame]=await Promise.all([mod.renderBuilderCard(payload),mod.renderProfile(payload),mod.renderProfile(payload,true)]);const blobs=await Promise.all([mod.canvasBlob(card),mod.canvasBlob(profile),mod.canvasBlob(frame)]);return{mod,blobs};}
  async function runExport(kind:"card"|"profile"|"frame"|"all"){if(!canExport){toast.error(photo?"Complete your name, role, and stack first.":"Upload a photo first.");return}setExporting(kind);try{const{mod,blobs}=await createAssets();if(kind==="all"){const JSZip=(await import("jszip")).default;const zip=new JSZip();zip.file(`hh-goa-2026-${slug}-builder-card.png`,blobs[0]);zip.file(`hh-goa-2026-${slug}-profile.png`,blobs[1]);zip.file("hh-goa-2026-profile-frame-transparent.png",blobs[2]);mod.downloadBlob(await zip.generateAsync({type:"blob"}),`hh-goa-2026-${slug}-builder-kit.zip`)}else{const idx={card:0,profile:1,frame:2}[kind];const names={card:`hh-goa-2026-${slug}-builder-card.png`,profile:`hh-goa-2026-${slug}-profile.png`,frame:"hh-goa-2026-profile-frame-transparent.png"};mod.downloadBlob(blobs[idx],names[kind])}toast.success(kind==="all"?"Builder kit downloaded.":"High-resolution PNG downloaded.")}catch(e){toast.error(e instanceof Error?e.message:"Export failed. Please try again.")}finally{setExporting(null)}}
  async function share(){if(!canExport){toast.error("Finish your builder identity before sharing.");return}const pendingWindow=typeof navigator.share!=="function"?window.open("about:blank","_blank"):null;if(pendingWindow)pendingWindow.opener=null;setExporting("share");try{const{mod,blobs}=await createAssets();const file=new File([blobs[0]],`hh-goa-2026-${slug}-builder-card.png`,{type:"image/png"});if(navigator.share&&navigator.canShare?.({files:[file]})){pendingWindow?.close();await navigator.share({files:[file],text:SHARE_CAPTION,title:"HH Goa 2026 Builder Identity"});toast.success("Share sheet opened with your PNG.");return}try{const body=new FormData();body.append("image",file);const res=await fetch("/api/share",{method:"POST",body});if(res.ok){const data=await res.json() as {url:string};if(pendingWindow)pendingWindow.location.href=xIntent(data.url);else window.open(xIntent(data.url),"_blank","noopener,noreferrer");toast.success("Persistent share page created.");return}}catch{}mod.downloadBlob(blobs[0],file.name);await navigator.clipboard?.writeText(SHARE_CAPTION);if(pendingWindow)pendingWindow.location.href=xIntent();else window.open(xIntent(),"_blank","noopener,noreferrer");toast.info("PNG downloaded and caption copied. Attach the downloaded image in X.",{duration:7000})}catch(e){pendingWindow?.close();if(e instanceof DOMException&&e.name==="AbortError")return;toast.error("Sharing did not complete. Try Download Card instead.")}finally{setExporting(null)}}
  const setField=<K extends keyof BuilderDetails>(key:K,value:BuilderDetails[K])=>setDetails(d=>({...d,[key]:value}));
  const toggleStack=(value:string)=>setDetails(d=>({...d,stack:d.stack.includes(value)?d.stack.filter(s=>s!==value):d.stack.length<5?[...d.stack,value]:d.stack}));
  const goGenerator=()=>document.getElementById("generator")?.scrollIntoView({behavior:reduce?"auto":"smooth"});

  return <main><Toaster theme="dark" position="top-center" richColors/>
    <header className="site-header"><a href="#top" className="brand">HH<span>GOA</span><small>2026</small></a><div className="header-stamp">GOA, INDIA · 28–31 OCT 2026</div><button className="quiet-button" onClick={goGenerator}>CREATE ID <ChevronRight size={16}/></button></header>
    <section className="hero" id="top"><div className="sun-orb"/><motion.div className="hero-copy" initial={reduce?false:{opacity:0,y:18}} animate={{opacity:1,y:0}}><div className="eyebrow">TASK 01 / BUILDER LOG</div><h1>Your HH Goa 2026<br/><em>Logbook Entry.</em></h1><p>No filters, no fluff — just your photo, stamped with the real HH Goa 2026 identity. Download it, post it, <b>#FrameInGoa.</b></p><div className="hero-actions"><button className="primary-button" onClick={goGenerator}>CREATE MY BUILDER IDENTITY <ArrowDown size={18}/></button><button className="secondary-button" onClick={()=>{document.getElementById("example")?.scrollIntoView({behavior:"smooth"})}}>VIEW EXAMPLE</button></div><small>No signup. No noise. Your photo stays yours until you hit share.</small></motion.div>
      <div className="hero-art" id="example"><div className="sample-card"><span>GOA, INDIA · 28–31 OCT 2026</span><b>#0247</b><h2>SHIP OR SHIP.</h2><p>day 03 — build day</p><div className="sample-sun"/><footer>#FRAMEINGOA <i>गोवा</i></footer></div><div className="sample-frame"><span>HH GOA</span><b>गोवा</b></div></div><div className="hero-horizon"/></section>
    <section className="generator-section" id="generator"><div className="section-heading"><span>01—04 / YOUR ENTRY</span><h2>Build it in one flow.</h2><p>Upload, crop, identify, export. Your original photo never leaves this device unless you choose Share.</p></div>
      <div className="workspace"><div className="controls-panel"><nav className="steps" aria-label="Generator steps">{([[1,"PHOTO"],[2,"CROP"],[3,"DETAILS"],[4,"EXPORT"]] as const).map(([n,label])=><button key={n} onClick={()=>n<=step&&setStep(n)} className={step===n?"active":step>n?"done":""}><span>{step>n?<Check size={14}/>:`0${n}`}</span>{label}</button>)}</nav>
        <AnimatePresence mode="wait" initial={false}><motion.div key={step} className="step-content" initial={reduce?false:{opacity:0,x:10}} animate={{opacity:1,x:0}} exit={reduce?{}:{opacity:0,x:-10}} transition={{duration:.18}}>
          {step===1&&<><div className="step-kicker">SOURCE / LOCAL ONLY</div><h3>Choose your photo.</h3><p className="step-copy">Portraits work best, but we’ll handle landscape and square images too.</p><div {...getRootProps()} className={`drop-zone ${isDragActive?"dragging":""}`}><input {...getInputProps()}/><div className="upload-mark"><ImagePlus/></div><strong>{processing?"Processing photo…":"Drop your signal here"}</strong><span>JPG, PNG, WEBP, HEIC · max 20 MB</span><button className="primary-button compact" type="button" onClick={open} disabled={processing}><Upload size={17}/> CHOOSE PHOTO</button><small><Clipboard size={13}/> You can also paste an image</small></div><button className="camera-button" type="button" onClick={open}><Camera size={18}/> Open camera or photo library</button></>}
          {step===2&&photo&&<><div className="step-kicker">CROP / TWO FORMATS</div><h3>Frame the shot.</h3><p className="step-copy">Each crop is saved independently. Keep your face inside the safe area.</p><div className="segmented"><button className={mode==="card"?"active":""} onClick={()=>setMode("card")}>ID CARD</button><button className={mode==="profile"?"active":""} onClick={()=>setMode("profile")}>PROFILE FRAME</button></div><CropEditor image={photo} mode={mode} value={currentCrop} onChange={setCurrentCrop}/><div className="step-actions"><button className="secondary-button" onClick={()=>setStep(1)}>REPLACE</button><button className="primary-button" onClick={()=>setStep(3)}>USE THIS CROP <ChevronRight size={17}/></button></div></>}
          {step===3&&<><div className="step-kicker">IDENTITY / FAST FIELDS</div><h3>What are you building as?</h3><label className="field"><span>NAME <b>{details.name.length}/38</b></span><input value={details.name} maxLength={38} placeholder="Your name" onChange={e=>setField("name",e.target.value.replace(/[<>]/g,""))}/></label><div className="field"><span>PRIMARY ROLE</span><div className="chips">{roleSuggestions.map(r=><button key={r} className={details.role===r?"selected":""} onClick={()=>setField("role",r)}>{r}</button>)}</div><input value={details.role} maxLength={40} placeholder="Or type a custom role" onChange={e=>setField("role",e.target.value.replace(/[<>]/g,""))}/></div><div className="field"><span>PRIMARY STACK <b>{details.stack.length}/5</b></span><div className="chips">{stackSuggestions.map(s=><button key={s} className={details.stack.includes(s)?"selected":""} onClick={()=>toggleStack(s)}>{s}</button>)}</div><input placeholder="Add custom technology + Enter" maxLength={24} onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();const v=e.currentTarget.value.trim().replace(/[<>]/g,"");if(v&&!details.stack.includes(v)&&details.stack.length<5){toggleStack(v);e.currentTarget.value=""}}}}/></div><div className="field-grid"><label className="field"><span>GITHUB <small>OPTIONAL</small></span><input value={details.github} maxLength={39} placeholder="username" onChange={e=>setField("github",e.target.value.replace(/[^a-zA-Z0-9_-]/g,""))}/></label><label className="field"><span>X <small>OPTIONAL</small></span><input value={details.x} maxLength={39} placeholder="username" onChange={e=>setField("x",e.target.value.replace(/[^a-zA-Z0-9_]/g,""))}/></label></div><label className="field"><span>BUILDER STATEMENT <b>{details.statement.length}/90</b></span><textarea value={details.statement} maxLength={90} placeholder="What are you here to ship?" onChange={e=>setField("statement",e.target.value.replace(/[<>]/g,""))}/></label><div className="generated-title"><span>GENERATED BUILDER TITLE</span><strong>{title}</strong><button aria-label="Reroll builder title" onClick={()=>setReroll(r=>r+1)}><RefreshCw size={16}/></button></div>{!valid.success&&details.name&&<p className="validation" role="alert">{valid.error.issues[0]?.message}</p>}<button className="primary-button full" onClick={()=>valid.success?setStep(4):toast.error(valid.error?.issues[0]?.message||"Complete the required details.")}>GENERATE MY IDENTITY <Sparkles size={17}/></button></>}
          {step===4&&<><div className="step-kicker">EXPORT / REAL PNG</div><h3>Your builder kit is ready.</h3><p className="step-copy">Exact-size PNGs, rendered from a dedicated high-resolution canvas.</p><div className="export-list"><button onClick={()=>void runExport("card")}><span><b>Builder ID Card</b><small>1080 × 1350 PNG</small></span><Download/></button><button onClick={()=>void runExport("profile")}><span><b>Profile Picture</b><small>1080 × 1080 PNG</small></span><Download/></button><button onClick={()=>void runExport("frame")}><span><b>Transparent Frame</b><small>1080 × 1080 PNG</small></span><Layers3/></button><button className="zip" onClick={()=>void runExport("all")}><span><b>{exporting?"Rendering your kit…":"Download Everything"}</b><small>All three files in a ZIP</small></span><Download/></button></div><div className="share-box"><h4>Ready to frame in Goa?</h4><p>On supported phones, the real PNG is sent to your native share sheet. Otherwise we create a share page or explain the manual fallback.</p><button className="x-button" onClick={()=>void share()} disabled={Boolean(exporting)}><Share2 size={18}/> SHARE TO X</button><button className="copy-button" onClick={async()=>{await navigator.clipboard.writeText(SHARE_CAPTION);toast.success("Caption copied.")}}><Clipboard size={16}/> COPY CAPTION</button></div></>}
        </motion.div></AnimatePresence></div>
        <aside className="preview-panel"><div className="preview-toolbar"><div className="segmented"><button className={mode==="card"?"active":""} onClick={()=>setMode("card")}>ID CARD</button><button className={mode==="profile"?"active":""} onClick={()=>setMode("profile")}>PROFILE</button></div><span>LIVE / {mode==="card"?"1080×1350":"1080×1080"}</span></div><motion.div className="preview-stage" layout><AnimatePresence mode="wait"><motion.div key={`${mode}-${theme}`} initial={reduce?false:{opacity:0,scale:.97}} animate={{opacity:1,scale:1}} exit={reduce?{}:{opacity:0,scale:.98}}><BuilderPreview image={photo} details={details} title={title} number={number} theme={theme} mode={mode} cropPosition={cropPosition}/></motion.div></AnimatePresence></motion.div><div className="theme-picker"><span>DAY LOG</span><div>{Object.values(themes).map(t=><button key={t.id} className={theme===t.id?"active":""} onClick={()=>setTheme(t.id)}><i style={{background:`linear-gradient(135deg,${t.accentA},${t.accentB})`}}/> {t.name}</button>)}</div></div></aside>
      </div></section>
    <footer className="site-footer"><div className="footer-mark">HH<span>GOA</span></div><p>Less Noise. More Signal.</p><div>GOA, INDIA · 28–31 OCT 2026<br/><span>2:47 pm Studio · गोवा</span></div></footer>
  </main>;
}
